//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sheddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignIn
    {
        public int SignIn_Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string activationcode { get; set; }
        public Nullable<System.DateTime> logindate { get; set; }
        public string expiretime { get; set; }
        public Nullable<int> active { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
